### ISSUE TITLE
Suggestion: Reload multiple tabs should unsuspend all of them

### ISSUE THREAD

**Issue by GetoXs** [gioxx/MarvellousSuspender#158]
Please complete the following information when submitting a feature request or bug report.
 * Extension version:7.1.6.2
 * Browser name & version: 96.0.4664.110
 * Operating system & version: Windows 10

When you select multiple suspended tabs and do Reload (Ctrl+R), just active tab will unsuspend. It would be very handy if all of them would unsuspend.

**Comment by gioxx** [comment]
This is from 2021 (v7.1.6.2), well before the MV2→MV3 rewrite. The current reload-detection mechanism tracks each tab individually via `chrome.tabs.onUpdated`, which should handle multiple selected tabs unsuspending independently regardless of how many were reloaded together. Could you retest this on a current version (9.0.1+) and confirm whether it's still happening? If so, we'll dig into it properly, but there's a decent chance this was fixed as a side effect of the rewrite.

**Comment by GetoXs** [comment]
Unfortunately, it still doesn't work. Selecting several tabs at the same time and then pressing Ctrl+R only reloads the "extention page" (including active tab).
Multiple active tabs example: 
<img width="1363" height="344" alt="Image" src="https://github.com/user-attachments/assets/027b96c7-a385-44f4-92d1-213fab574576" />
I noticed another effect that may be related: if I reload/refresh an inactive tab in Chrome, nothing happens and the page is suspended.

<img width="1075" height="471" alt="Image" src="https://github.com/user-attachments/assets/5856d81f-a11e-4a35-9218-a3953cf86793" />

FYI. testes with v. 9.0.1

**Comment by gioxx** [comment]
Thanks for retesting on 9.0.1, @GetoXs. Two things here worth separating: the multi-tab reload not unsuspending all selected tabs (the original ask), and reloading a single *inactive* suspended tab doing nothing at all, that second one sounds like a real bug rather than an enhancement. Going to look into both, will follow up here.

**Comment by gioxx** [comment]
Dug into this. It's not really a bug, it's a deliberate guard that goes back to the original TGS codebase (`suspended.js`, present since well before the MV3 rewrite): the page only remembers "I was explicitly reloaded" (the trigger that unsuspends on the next check) when it's the *currently focused* tab at unload time. Background tabs skip that step on purpose, because Chrome can also unload/discard a background tab on its own (memory pressure, or TMS's own inactive-tab discard), and that's not the same as you asking for it back.

Side effect: reloading a background tab, on its own or as part of a multi-select Ctrl+R, never counts as "please unsuspend me," only the active tab does. Explains both things you saw.

Making this work for background tabs needs a way to tell "system discarded this" apart from "user explicitly hit Reload while it was inactive," which the current focus-only check can't do on its own. Might be worth an opt-in setting for people who want reload-to-unsuspend to apply even to background tabs, rather than changing default behavior, still thinking through whether that's the right shape. Will follow up here once there's something concrete.

Also, thanks, chasing this down the log buffer wasn't behaving right, turned up a separate bug: `captureLogs` was silently going blind after the extension's first Service Worker restart of a browser session, so most debug reports we'd have asked for on issues like this were losing data mid-session. Fixed as a side effect of digging into this one 😂

**Comment by GetoXs** [comment]
As a developer, I admit that I was worried about this mechanism. Oh well, it remains an unresolved feature request.
It's great that we managed to catch another bug along the way!

**Comment by gioxx** [comment]
Just to close the loop on one thing: would an opt-in setting for this (reload-to-unsuspend working on background tabs too, off by default) actually be useful to you, or was the multi-select Ctrl+R just a one-off thing you tried? Don't want to build it unless it's something you'd actually use.

**Comment by GetoXs** [comment]
If it worked with expense of greater memory usage (e.g. by disabling Chrome's mechanisms for suspending unused tabs), then no.
But if not, then it would be useful, both through Ctrl+R and "right-click -> Reload" sounds good. Do you see any other options?

**Comment by gioxx** [comment]
Good news, no memory tradeoff: this doesn't touch Chrome's or TMS's own background-tab discarding at all, those are separate mechanisms untouched by this change. It only affects whether a reload on a background tab gets *recognized* as "please unsuspend" once it happens, nothing about when/whether tabs get discarded in the first place.

No other real option on the table, the current code only has one detection point for this (the same `beforeunload` check used for the active-tab case), so it's this approach or nothing. Both Ctrl+R and right-click → Reload go through the same code path, so both would work the same way once this ships. I'll build it as opt-in and follow up here once it's ready to test.

**Comment by GetoXs** [comment]
Great! For me, this flow is a natural UX-wise behaviour for this extension. Let me know when it's ready for testing, I'd be happy to help.

**Comment by gioxx** [comment]
I'd be more than happy to. I'm just taking a few days off to spend time with my wife and kids and enjoy the beach a bit, but then I'll be back up and running and can get to work on it 😄

**Comment by GetoXs** [comment]
No problem, keep the right priorities💪

**Comment by gioxx** [comment]
The exact feature you asked for, "reload also unsuspends background tabs", shipped in 9.0.3 as an opt-in setting (Options → General → "Reload also unsuspends tabs in the background"). Thanks for flagging this originally, GetoXs. Closing, please reopen if it doesn't behave as expected on a current version.

**Comment by GetoXs** [comment]
Thanks for an update!
